/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CrearProductoController;
import Controller.EliminarProductoController;
import Controller.ProductoController;
import Model.ListadoInventario;
import java.awt.Image;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author 4784.joan23
 */
public class MostrarProducto extends javax.swing.JFrame {
    CrearProductoController crearProducto = new CrearProductoController();
    ProductoController mostrarProducto = new ProductoController();
    int posicion = 0;
    int j = 0;
    ArrayList<ListadoInventario> miLista = mostrarProducto.mostrarListadoProductos();

    /**
     * Creates new form MostrarProducto
     */
    public MostrarProducto() {
        initComponents();
        this.jlPedirStock.setVisible(false);
        this.jbGuardar.setEnabled(false);
        this.jtTablaProductos.setModel(mostrarProducto.mostrarProducto());
        for (int i = 0; i < jtTablaProductos.getColumnCount(); i++) {
            if (i != 1 && i != 7 && i != 8 && i != 9) {
                jtTablaProductos.getColumnModel().getColumn(i).setMaxWidth(0);
                jtTablaProductos.getColumnModel().getColumn(i).setMinWidth(0);
                jtTablaProductos.getTableHeader().getColumnModel().getColumn(i).setMaxWidth(0);
                jtTablaProductos.getTableHeader().getColumnModel().getColumn(i).setMinWidth(0);
            }
        }

        this.jtNombre.setText(miLista.get(0).getProd_nom());
        this.jtPrecio.setText(miLista.get(0).getProd_preu());
        
        this.jcbCategoria.setSelectedItem('"'+miLista.get(0).getCategoria_nom()+'"');
        this.jcbSerie.setSelectedItem('"'+miLista.get(0).getSerie_nom()+'"');
        this.jcNumBloque.setSelectedItem('"'+miLista.get(0).getNum_bloc()+'"');
        this.jcNumeroPasillo.setSelectedItem('"'+miLista.get(0).getNum_passadis()+'"');
        this.jcNumEstanteria.setSelectedItem('"'+miLista.get(0).getNum_lleixa()+'"');
        
        /*JOptionPane.showMessageDialog(null, miLista.get(0).getCategoria_nom());
        JOptionPane.showMessageDialog(null, miLista.get(0).getSerie_nom());
        JOptionPane.showMessageDialog(null, miLista.get(0).getNum_bloc());
        JOptionPane.showMessageDialog(null, miLista.get(0).getNum_passadis());
        JOptionPane.showMessageDialog(null, miLista.get(0).getNum_lleixa());*/
        
        this.jtDescuento.setText(miLista.get(0).getProd_descompte());
        this.jtStockMinimo.setText(miLista.get(0).getEstoc_q_min());
        this.jtStockActual.setText(miLista.get(0).getEstoc_q_actual());
        this.jtStockMaximo.setText(miLista.get(0).getEstoc_q_max());
        this.jtDescripcion.setText(miLista.get(0).getProd_descripcio());
        
        this.jtNombre.setEditable(false);
        this.jtPrecio.setEditable(false);
        this.jtDescuento.setEditable(false);
        this.jtStockMinimo.setEditable(false);
        this.jtStockActual.setEditable(false);
        this.jtStockMaximo.setEditable(false);
        this.jtDescripcion.setEditable(false);
        this.jcNumBloque.setEditable(false);
        this.jcNumeroPasillo.setEditable(false);
        this.jcNumEstanteria.setEditable(false);
        this.jcbCategoria.setEditable(false);
        this.jcbSerie.setEditable(false);
        
        
        String ruta = "../Img/" + miLista.get(0).getProd_foto();
        URL url = this.getClass().getResource(ruta);
        ImageIcon icon = new ImageIcon(url);
        ImageIcon foto = new ImageIcon(icon.getImage().getScaledInstance(jlFoto.getWidth(), jlFoto.getHeight(), Image.SCALE_DEFAULT));
        jlFoto.setIcon(foto);
        
        crearProducto.llenarComboCategoria(jcbCategoria);
        crearProducto.llenarComboSerie(jcbSerie);
        crearProducto.llenarComboLugar(jcNumBloque,jcNumeroPasillo,jcNumEstanteria);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtTablaProductos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jlFoto = new javax.swing.JLabel();
        jbPrimero = new javax.swing.JButton();
        jbAnterior = new javax.swing.JButton();
        jbSiguiente = new javax.swing.JButton();
        jbUltimo = new javax.swing.JButton();
        jbMenu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtStockMinimo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtStockActual = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jlPedirStock = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtDescripcion = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jcbCategoria = new javax.swing.JComboBox<>();
        jbEditar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jcbSerie = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jtStockMaximo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtPrecio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtDescuento = new javax.swing.JTextField();
        jcNumEstanteria = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jcNumeroPasillo = new javax.swing.JComboBox<>();
        jcNumBloque = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtTablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Producto_id", "Nombre", "Serie", "Descuento", "Stock Minimo", "Stock Actual", "Stock Maximo", "Precio", "Num Bloc", "Num Passadis", "Num Lleixa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtTablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTablaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtTablaProductos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
        );

        jbPrimero.setText("PRIMERO");
        jbPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPrimeroActionPerformed(evt);
            }
        });

        jbAnterior.setText("ANTERIOR");

        jbSiguiente.setText("SIGUIENTE");

        jbUltimo.setText("ULTIMO");

        jbMenu.setText("MENU");
        jbMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMenuActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRODUCTO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setText("Nombre:");

        jLabel6.setText("Stock Mínimo:");

        jtStockMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtStockMinimoActionPerformed(evt);
            }
        });

        jLabel7.setText("Stock Actual:");

        jtStockActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtStockActualActionPerformed(evt);
            }
        });

        jLabel5.setText("Serie:");

        jlPedirStock.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jlPedirStock.setForeground(new java.awt.Color(255, 0, 0));
        jlPedirStock.setText("HAY QUE PEDIR STOCK");
        jlPedirStock.setToolTipText("");

        jLabel2.setText("Descripción:");

        jtDescripcion.setColumns(20);
        jtDescripcion.setRows(5);
        jScrollPane2.setViewportView(jtDescripcion);

        jLabel9.setText("Categoria:");

        jcbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCategoriaActionPerformed(evt);
            }
        });

        jbEditar.setText("EDITAR");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbEliminar.setBackground(new java.awt.Color(255, 51, 51));
        jbEliminar.setText("ELIMINAR");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbGuardar.setText("GUARDAR");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbNuevo.setBackground(new java.awt.Color(51, 255, 51));
        jbNuevo.setText("NUEVO");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jcbSerie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Stock Máximo:");

        jtStockMaximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtStockMaximoActionPerformed(evt);
            }
        });

        jLabel3.setText("Precio:");

        jLabel4.setText("Descuento:");

        jcNumEstanteria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setText("Numero Bloque:");

        jLabel11.setText("Numero Estanteria:");

        jcNumeroPasillo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcNumBloque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setText("Numero Pasillo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(18, 18, 18)
                            .addComponent(jcNumBloque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jcNumeroPasillo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jcNumEstanteria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jbNuevo))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(48, 48, 48)
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(jtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jtStockMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jlPedirStock, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtStockActual, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtStockMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(137, 137, 137)
                            .addComponent(jbEliminar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(57, 57, 57)
                            .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jcbSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtStockMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jtStockActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jtStockMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlPedirStock)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jcNumBloque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcNumeroPasillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jcNumEstanteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbGuardar)
                        .addComponent(jbNuevo)
                        .addComponent(jbEliminar))
                    .addComponent(jbEditar))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbPrimero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jbPrimero)
                        .addGap(26, 26, 26)
                        .addComponent(jbAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSiguiente)
                        .addGap(31, 31, 31)
                        .addComponent(jbUltimo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtStockActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtStockActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtStockActualActionPerformed

    private void jbMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMenuActionPerformed
        // BOTON MENÚ
        dispose();
        VentanaPrincipal ventanaPrincipal = new VentanaPrincipal();
        ventanaPrincipal.setVisible(true);

    }//GEN-LAST:event_jbMenuActionPerformed

    private void jtTablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTablaProductosMouseClicked
        // AL CLICKAR LA TABLA
        int fila = this.jtTablaProductos.rowAtPoint(evt.getPoint());

        this.jtNombre.setText(String.valueOf(this.jtTablaProductos.getValueAt(fila, 1)));
        this.jtPrecio.setText(String.valueOf(this.jtTablaProductos.getValueAt(fila, 5)));
        this.jtDescuento.setText(String.valueOf(this.jtTablaProductos.getValueAt(fila, 4)));
        this.jtStockMinimo.setText(String.valueOf(this.jtTablaProductos.getValueAt(fila, 10)));
        this.jtStockActual.setText(String.valueOf(this.jtTablaProductos.getValueAt(fila, 11)));
        this.jtStockMaximo.setText(String.valueOf(this.jtTablaProductos.getValueAt(fila, 12)));
        this.jtDescripcion.setText(String.valueOf(this.jtTablaProductos.getValueAt(fila, 3)));
        
        this.jcbCategoria.setSelectedItem(this.jtTablaProductos.getValueAt(fila, 13));
        this.jcbSerie.setSelectedItem(this.jtTablaProductos.getValueAt(fila, 6));
        this.jcNumBloque.setSelectedItem(this.jtTablaProductos.getValueAt(fila, 7));
        this.jcNumeroPasillo.setSelectedItem(this.jtTablaProductos.getValueAt(fila, 8));
        this.jcNumEstanteria.setSelectedItem(this.jtTablaProductos.getValueAt(fila, 9));
        
        String ruta = "../Img/" + this.jtTablaProductos.getValueAt(fila, 2);
        URL url = this.getClass().getResource(ruta);
        ImageIcon icon = new ImageIcon(url);
        ImageIcon foto = new ImageIcon(icon.getImage().getScaledInstance(jlFoto.getWidth(), jlFoto.getHeight(), Image.SCALE_DEFAULT));
        jlFoto.setIcon(foto);

        int stockMinimo = Integer.valueOf(this.jtStockMinimo.getText());
        int stockActual = Integer.valueOf(this.jtStockActual.getText());
        if (stockMinimo > stockActual) {
            this.jlPedirStock.setVisible(true);
        } else {
            this.jlPedirStock.setVisible(false);
        }
        this.jbPrimero.setEnabled(true);
        this.jbAnterior.setEnabled(true);
        this.jbSiguiente.setEnabled(true);
        this.jbUltimo.setEnabled(true);
        this.jbMenu.setEnabled(true);
        this.jbEliminar.setEnabled(true);
        this.jbNuevo.setEnabled(true);
        this.jbMenu.setEnabled(true);
        this.jbGuardar.setEnabled(false);

        /*this.tnom.setEditable(true);
        this.tserie.setEditable(true);
        this.tstockactual.setEditable(true);
        this.tstockmax.setEditable(true);
        this.tstockmin.setEditable(true);
        this.jComboBox1.setVisible(true);
        this.jComboBox2.setVisible(true);
        this.jComboBox3.setVisible(true);
        this.jComboBox4.setVisible(true);

        /*this.tnom.setEditable(false);
            this.tserie.setEditable(false);
            this.tstockactual.setEditable(false);
            this.tstockmax.setEditable(false);
            this.tstockmin.setEditable(false);
            this.tbloc.setEditable(false);
            this.tcat.setEditable(false);
            this.tpasadizo.setEditable(false);
            this.testanteria.setEditable(false);*/
 /*this.btadd_mod.setText("Modificar");
        this.bteliminar.setEnabled(true);*/
        //al darle clic en la tabla, los combo box desaparecen
        /*this.jComboBox1.setVisible(false);
        this.jComboBox2.setVisible(false);
        this.jComboBox3.setVisible(false);
        this.jComboBox4.setVisible(false);*/
    }//GEN-LAST:event_jtTablaProductosMouseClicked

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        // BOTON EDITAR
        this.jbPrimero.setEnabled(false);
        this.jbAnterior.setEnabled(false);
        this.jbSiguiente.setEnabled(false);
        this.jbUltimo.setEnabled(false);
        this.jbEliminar.setEnabled(false);
        this.jbNuevo.setEnabled(false);
        this.jbGuardar.setEnabled(true);
        this.jbEditar.setEnabled(false);
        
        this.jtNombre.setEditable(true);
        this.jtPrecio.setEditable(true);
        this.jtDescuento.setEditable(true);
        this.jtStockMinimo.setEditable(true);
        this.jtStockActual.setEditable(true);
        this.jtStockMaximo.setEditable(true);
        this.jtDescripcion.setEditable(true);
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jtStockMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtStockMinimoActionPerformed
        // JTextField Stock Mínimo

    }//GEN-LAST:event_jtStockMinimoActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // Boton Eliminar
        EliminarProductoController eliminarProducto = new EliminarProductoController();
        

    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPrimeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbPrimeroActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        // BOTON NUEVO
        dispose();
        AltaProducto ventanaAltaProducto = new AltaProducto();
        ventanaAltaProducto.setVisible(true);

    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jcbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbCategoriaActionPerformed

    private void jtStockMaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtStockMaximoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtStockMaximoActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // BOTON GUARDAR
    }//GEN-LAST:event_jbGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbAnterior;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbMenu;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbPrimero;
    private javax.swing.JButton jbSiguiente;
    private javax.swing.JButton jbUltimo;
    private javax.swing.JComboBox<String> jcNumBloque;
    private javax.swing.JComboBox<String> jcNumEstanteria;
    private javax.swing.JComboBox<String> jcNumeroPasillo;
    private javax.swing.JComboBox<String> jcbCategoria;
    private javax.swing.JComboBox<String> jcbSerie;
    private javax.swing.JLabel jlFoto;
    private javax.swing.JLabel jlPedirStock;
    private javax.swing.JTextArea jtDescripcion;
    private javax.swing.JTextField jtDescuento;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtPrecio;
    private javax.swing.JTextField jtStockActual;
    private javax.swing.JTextField jtStockMaximo;
    private javax.swing.JTextField jtStockMinimo;
    private javax.swing.JTable jtTablaProductos;
    // End of variables declaration//GEN-END:variables
}
