/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Model;

import controlador.ControllerAlmacen;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Categoria;
import Model.Conexion;
import model.Lugar;
import model.Producto;
import model.Stock;

/**
 *
 * @author Usuario
 */
public class vistaProducto extends javax.swing.JInternalFrame {
    
    ControllerAlmacen producto = new ControllerAlmacen();
    /**
     * Creates new form vistaProducto
     */
    
    public DefaultTableModel mostrarPersona(){
        String vectorPersona[]= new String[2];
          vectorPersona[0] = "nombre";
        vectorPersona[1]="pasword";
         Conexion conecControl = new Conexion();
        Connection cn = conecControl.conectar();
        
        String sql = "SELECT * from  tbl_personas";
        
        Statement st = null;
        ResultSet rs = null;
     DefaultTableModel   muestra = new DefaultTableModel(null,vectorPersona);
      try {
            
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            
            while (rs.next()) {
                
                vectorPersona[0] = rs.getString("persona_usuario");
                vectorPersona[1] = rs.getString("persona_password");
               
                
              muestra.addRow(vectorPersona);
            }
      
        } catch (Exception e) {
        }
        
        return muestra;
   
    }
    
    public vistaProducto() {
        initComponents();
        
        //this.setLocationRelativeTo(null);
        this.jTable3.setModel(mostrarPersona());
        this.jTable1.setModel(producto.mostrarProducto());
        producto.ocultarColumna(7, jTable1);
        producto.ocultarColumna(8, jTable1);
        producto.ocultarColumna(9, jTable1);
        producto.ocultarColumna(10, jTable1);
        producto.ocultarColumna(11, jTable1);
        producto.ocultarColumna(12, jTable1);
        
        this.jTable2.setModel(producto.mostrarLocalizacion());
        producto.llenarCombo(jComboBox1);
        
        /*this.tcat.setVisible(true);
        this.tbloc.setVisible(true);
        this.tpasadizo.setVisible(true);
        this.testanteria.setVisible(true);*/
        
        /*this.tidcat.setVisible(false);
        this.jComboBox1.setVisible(false);
        this.jComboBox2.setVisible(false);
        this.jComboBox3.setVisible(false);
        this.jComboBox4.setVisible(false);*/
        
        this.tid.setText("");
        this.tid.setEnabled(false);
        this.tnom.setText("");
        this.tserie.setText("");
        this.tstockactual.setText("");
        this.tstockmax.setText("");
        this.tstockmin.setText("");
        this.tcat.setText("");
        this.tcat.setEditable(false);
        this.tidcat.setText("");
        this.tidcat.setEnabled(false);
        this.tbloc.setText("");
        this.tbloc.setEditable(false);
        this.tpasadizo.setText("");
        this.tpasadizo.setEditable(false);
        this.testanteria.setText("");
        this.testanteria.setEditable(false);
        
        this.bteliminar.setEnabled(false);
        
        if(this.btadd_mod.getText()== "Añadir"){
            this.btadd_mod.setEnabled(true);
        }
        
        this.aerror.setVisible(false);
        this.aerror.setEditable(false);
        
        this.estocid.setVisible(false);
        this.llocid.setVisible(false);
        
        this.tbusop.setVisible(false);
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pform = new javax.swing.JPanel();
        tnom = new javax.swing.JTextField();
        tid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tserie = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tidcat = new javax.swing.JTextField();
        tstockactual = new javax.swing.JTextField();
        tstockmin = new javax.swing.JTextField();
        tstockmax = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        tbloc = new javax.swing.JTextField();
        tpasadizo = new javax.swing.JTextField();
        testanteria = new javax.swing.JTextField();
        tcat = new javax.swing.JTextField();
        btnuevo = new javax.swing.JButton();
        btadd_mod = new javax.swing.JButton();
        bteliminar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        aerror = new javax.swing.JTextArea();
        estocid = new javax.swing.JTextField();
        llocid = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        ptabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        tbuscar = new javax.swing.JTextField();
        btbuscar = new javax.swing.JButton();
        jComboBox5 = new javax.swing.JComboBox<>();
        tbusop = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Productos"));
        setClosable(true);
        setIconifiable(true);

        tid.setEditable(false);
        tid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidActionPerformed(evt);
            }
        });

        jLabel1.setText("ID Producto");

        jLabel2.setText("Nombre");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel3.setText("Serie");

        jLabel4.setText("Categoria");

        tidcat.setEditable(false);

        jLabel5.setText("Stock Act");

        jLabel6.setText("Stock Max.");

        jLabel7.setText("Stock Min.");

        jLabel8.setText("Bloque");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bloc 1", "Bloc 2", "Bloc 3", "Bloc 4", "Bloc 5", "Bloc 6", "Bloc 7", "Bloc 8" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jLabel9.setText("Pasadizo");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "passadis 1", "passadis 2", "passadis 3", "passadis 4", "passadis 5", "passadis 6", "passadis 7", "passadis 8", "passadis 9", "passadis 10", "passadis 11", "passadis 12" }));
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });

        jLabel10.setText("Estantería");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "lleixa 1", "lleixa 2", "lleixa 3", "lleixa 4", "lleixa 5", "lleixa 6", "lleixa 7", "lleixa 8" }));
        jComboBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox4ItemStateChanged(evt);
            }
        });

        btnuevo.setText("Nuevo");
        btnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuevoActionPerformed(evt);
            }
        });

        btadd_mod.setText("Añadir");
        btadd_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btadd_modActionPerformed(evt);
            }
        });

        bteliminar.setText("Eliminar");
        bteliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteliminarActionPerformed(evt);
            }
        });

        aerror.setColumns(20);
        aerror.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        aerror.setForeground(new java.awt.Color(255, 0, 0));
        aerror.setRows(5);
        jScrollPane3.setViewportView(aerror);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setText("nom");

        jLabel12.setText("passwd");

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pformLayout = new javax.swing.GroupLayout(pform);
        pform.setLayout(pformLayout);
        pformLayout.setHorizontalGroup(
            pformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pformLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pformLayout.createSequentialGroup()
                        .addGroup(pformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pformLayout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(tcat, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tidcat, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pformLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(estocid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(llocid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pformLayout.createSequentialGroup()
                                            .addGroup(pformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                                            .addGap(8, 8, 8)
                                            .addGroup(pformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tnom, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tserie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(pformLayout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(8, 8, 8)
                                            .addComponent(tstockactual, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tstockmax, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tstockmin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(7, 7, 7)))))
                            .addGroup(pformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pformLayout.createSequentialGroup()
                                    .addComponent(btnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(75, 75, 75)
                                    .addComponent(btadd_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bteliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(pformLayout.createSequentialGroup()
                        .addGroup(pformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pformLayout.createSequentialGroup()
                                .addGroup(pformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(11, 11, 11)
                                .addGroup(pformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tbloc, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(tpasadizo)))
                            .addGroup(pformLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(testanteria, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(pformLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(31, 31, 31)
                .addGroup(pformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(jTextField2))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pformLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addGap(43, 43, 43)
                .addComponent(jButton2))
        );
        pformLayout.setVerticalGroup(
            pformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pformLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(estocid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(llocid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tserie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(tstockmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tstockactual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tstockmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tcat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tidcat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tbloc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tpasadizo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(testanteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(pformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnuevo)
                    .addComponent(bteliminar)
                    .addComponent(btadd_mod))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(pformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(pformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(66, 66, 66)
                .addGroup(pformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ptabla.setBorder(javax.swing.BorderFactory.createTitledBorder("Info. Producto"));

        jTable1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout ptablaLayout = new javax.swing.GroupLayout(ptabla);
        ptabla.setLayout(ptablaLayout);
        ptablaLayout.setHorizontalGroup(
            ptablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ptablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ptablaLayout.setVerticalGroup(
            ptablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ptablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Localización Producto"));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
        );

        btbuscar.setText("Buscar");
        btbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbuscarActionPerformed(evt);
            }
        });

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nombre", "categoria" }));
        jComboBox5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox5ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ptabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btbuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbusop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btbuscar)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbusop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ptabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
       Categoria ca = (Categoria)this.jComboBox1.getSelectedItem();
       this.tidcat.setText(String.valueOf(ca.getCategoria_id()));
       this.tcat.setText(String.valueOf(ca.getCategoria_nom()));
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void tidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
        this.tbloc.setText((String)this.jComboBox2.getSelectedItem());
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int fila = this.jTable1.rowAtPoint(evt.getPoint());
        
        this.tid.setText(String.valueOf(this.jTable1.getValueAt(fila, 0)));
        
        this.estocid.setText(String.valueOf(this.jTable1.getValueAt(fila, 10)));
        this.llocid.setText(String.valueOf(this.jTable1.getValueAt(fila, 11)));
        
        this.tnom.setText((String) this.jTable1.getValueAt(fila, 1));
        this.tserie.setText((String) this.jTable1.getValueAt(fila, 2));
        this.tcat.setText((String) this.jTable1.getValueAt(fila, 3));
        this.tstockactual.setText(String.valueOf(this.jTable1.getValueAt(fila, 4)));
        this.tstockmax.setText(String.valueOf(this.jTable1.getValueAt(fila, 5)));
        this.tstockmin.setText(String.valueOf(this.jTable1.getValueAt(fila, 6)));
        
        this.tbloc.setText((String) this.jTable1.getValueAt(fila, 7));
        this.tpasadizo.setText((String) this.jTable1.getValueAt(fila, 8));
        this.testanteria.setText((String) this.jTable1.getValueAt(fila, 9));
        
        this.tidcat.setText(String.valueOf(this.jTable1.getValueAt(fila, 12)));
        
            this.tnom.setEditable(true);
            this.tserie.setEditable(true);
            this.tstockactual.setEditable(true);
            this.tstockmax.setEditable(true);
            this.tstockmin.setEditable(true);
            this.jComboBox1.setVisible(true);
            this.jComboBox2.setVisible(true);
            this.jComboBox3.setVisible(true);
            this.jComboBox4.setVisible(true);
            
        
            /*this.tnom.setEditable(false);
            this.tserie.setEditable(false);
            this.tstockactual.setEditable(false);
            this.tstockmax.setEditable(false);
            this.tstockmin.setEditable(false);
            this.tbloc.setEditable(false);
            this.tcat.setEditable(false);
            this.tpasadizo.setEditable(false);
            this.testanteria.setEditable(false);*/
        
        
        this.btadd_mod.setText("Modificar");
        this.bteliminar.setEnabled(true);
        
        //al darle clic en la tabla, los combo box desaparecen
        /*this.jComboBox1.setVisible(false);
        this.jComboBox2.setVisible(false);
        this.jComboBox3.setVisible(false);
        this.jComboBox4.setVisible(false);*/
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuevoActionPerformed
        // TODO add your handling code here:
       
        this.tid.setText("");
        this.tid.setEnabled(false);
        this.tnom.setText("");
        this.tnom.setEditable(true);
        this.tserie.setText("");
        this.tserie.setEditable(true);
        this.tstockactual.setText("");
        this.tstockactual.setEditable(true);
        this.tstockmax.setText("");
        this.tstockmax.setEditable(true);
        this.tstockmin.setText("");
        this.tstockmin.setEditable(true);
        this.tidcat.setEnabled(false);
        
        this.tcat.setText("");
        this.tidcat.setText("");
        this.tidcat.setVisible(true);
        this.tbloc.setText("");
        this.tpasadizo.setText("");
        this.testanteria.setText("");
        
        
        this.jComboBox1.setVisible(true);
        this.jComboBox2.setVisible(true);
        this.jComboBox3.setVisible(true);
        this.jComboBox4.setVisible(true);
        
        this.btadd_mod.setText("Añadir");
        
        this.bteliminar.setEnabled(false);
    }//GEN-LAST:event_btnuevoActionPerformed

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        // TODO add your handling code here:
        this.tpasadizo.setText((String)this.jComboBox3.getSelectedItem());
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox4ItemStateChanged
        // TODO add your handling code here:
        this.testanteria.setText((String)this.jComboBox4.getSelectedItem());
    }//GEN-LAST:event_jComboBox4ItemStateChanged

    private void btadd_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btadd_modActionPerformed
        String error = "";
        
            if (this.tnom.getText().length() == 0) {
                error += " - Campo NOMBRE obligatorio*";
            }
            
            if (this.tserie.getText().length() == 0) {
                error += "\n - Campo SERIE obligatorio*";
            }
            
            if (this.tstockactual.getText().length() == 0 && this.tstockmax.getText().length() == 0 && this.tstockmin.getText().length() == 0 ){
                error += "\n - Los campos de STOCK son obligatorios*";

            } else if (!ControllerAlmacen.isNumeric(this.tstockactual.getText()) || !ControllerAlmacen.isNumeric(this.tstockmax.getText()) || !ControllerAlmacen.isNumeric(this.tstockmin.getText())) {
                error += "\n - Los campos de STOCK deben ser numéricos*";    
            } 
            
            int sa = Integer.parseInt(this.tstockactual.getText());
                int sm = Integer.parseInt(this.tstockmin.getText());
                int sM = Integer.parseInt(this.tstockmax.getText());
        
            /*  if (sa > sM){
                error += "\n - El STOCK ACTUAL no puede ser mayor al STOCK MAX*";
            } else
            
            if (sa < sm){
                error += "\n - El STOCK ACTUAL no puede ser menor al STOCK min*";
            } else
            
            if (sm > sM){
                error += "\n - El STOCK MAX no puede ser menor al STOCK min*";
            }
            
            
            if (Integer.parseInt(this.tstockactual.getText()) < Integer.parseInt(this.tstockmin.getText())){
                error += "\n - El STOCK ACTUAL no puede ser menor al STOCK min*";
            } else if (Integer.parseInt(this.tstockactual.getText()) > Integer.parseInt(this.tstockmax.getText())){
                error += "\n - El STOCK ACTUAL no puede ser menor al STOCK MAX*";
            } else if (Integer.parseInt(this.tstockmax.getText()) < Integer.parseInt(this.tstockmin.getText())){
                error += "\n - El STOCK MAX no puede ser menor al STOCK min*";
            }
            
            if (!(sa > sm && sa < sM)){
                 error += "\n - Verifica que has introducido correctamente los campos de STOCK**";
            }*/
     
            if (this.tcat.getText().length() == 0){
                error += "\n - Campo CATEGORIA obligatorio*";
            }
            
            if (this.tbloc.getText().length() == 0 || this.tpasadizo.getText().length() == 0 || this.testanteria.getText().length() == 0 ){
                error += "\n - Asigne una LOCALIZACIÓN al producto*";
            }
        
        if ("".equals(error)){    

            if ("Añadir".equals(this.btadd_mod.getText())){

                    String nom = this.tnom.getText();
                    String serie = this.tserie.getText();
                    int cat = Integer.parseInt(this.tidcat.getText());
                    String bloc = this.tbloc.getText();
                    String pasadizo = this.tpasadizo.getText();
                    String estanteria = this.testanteria.getText();
                    int estoc_q_actual = Integer.parseInt(this.tstockactual.getText());
                    int estoc_q_max = Integer.parseInt(this.tstockmax.getText());
                    int estoc_q_min = Integer.parseInt(this.tstockmin.getText());

                    Producto p = new Producto(nom,serie,cat);
                    Lugar l = new Lugar(bloc,pasadizo,estanteria);
                    Stock s = new Stock(estoc_q_actual, estoc_q_min, estoc_q_max);

                    producto.addProdEstocLloc(p,l,s);
                    
                    this.jTable1.setModel(producto.mostrarProducto());
                    producto.ocultarColumna(7, jTable1);
                    producto.ocultarColumna(8, jTable1);
                    producto.ocultarColumna(9, jTable1);
                    producto.ocultarColumna(10, jTable1);
                    producto.ocultarColumna(11, jTable1);
                    producto.ocultarColumna(12, jTable1);
                    this.jTable2.setModel(producto.mostrarLocalizacion());
                    
            } else if ("Modificar".equals(this.btadd_mod.getText())){
                    
                /*this.tnom.setEditable(true);
                this.tserie.setEditable(true);
                this.tstockactual.setEditable(true);
                this.tstockmax.setEditable(true);
                this.tstockmin.setEditable(true);
                this.jComboBox1.setVisible(true);
                this.jComboBox2.setVisible(true);
                this.jComboBox3.setVisible(true);
                this.jComboBox4.setVisible(true);*/
                    
                    String nom = this.tnom.getText();
                    String serie = this.tserie.getText();
                    String cat = this.tcat.getText();
                    int catid = Integer.parseInt(this.tidcat.getText());
                    
                    String bloc = this.tbloc.getText();
                    String pasadizo = this.tpasadizo.getText();
                    String estanteria = this.testanteria.getText();
                    
                    int estoc_q_actual = Integer.parseInt(this.tstockactual.getText());
                    int estoc_q_max = Integer.parseInt(this.tstockmax.getText());
                    int estoc_q_min = Integer.parseInt(this.tstockmin.getText());
                    
                    int llocid = Integer.parseInt(this.llocid.getText());
                    int prodid = Integer.parseInt(this.tid.getText());

                    Producto p = new Producto(nom,serie,catid);
                    Lugar l = new Lugar(bloc,pasadizo,estanteria);
                    Stock es = new Stock(estoc_q_actual, estoc_q_min, estoc_q_max, prodid, llocid);
                     
                    int dialogButton = JOptionPane.YES_NO_OPTION;
                    int dialogResult = JOptionPane.showConfirmDialog (null, "¿Estas seguro de modificar el producto "+cat+": "+nom+"?","Warning",dialogButton);

                    if(dialogResult == 0){ 
                        producto.modProductoStockLloc(es, p, l);
                    
                        this.jTable1.setModel(producto.mostrarProducto());
                        producto.ocultarColumna(7, jTable1);
                        producto.ocultarColumna(8, jTable1);
                        producto.ocultarColumna(9, jTable1);
                        producto.ocultarColumna(10, jTable1);
                        producto.ocultarColumna(11, jTable1);
                        producto.ocultarColumna(12, jTable1);
                        this.jTable2.setModel(producto.mostrarLocalizacion());
                    } else {
                        return;
                    }
            }
            
        } else {
            this.aerror.setVisible(true);
            this.aerror.setText(error);
        }
    }//GEN-LAST:event_btadd_modActionPerformed

    private void bteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminarActionPerformed
        // TODO add your handling code here:
       // int estocid = Integer.parseInt(this.estocid.getText());
        int llocid = Integer.parseInt(this.llocid.getText());
        int prodid = Integer.parseInt(this.tid.getText());
        String nom = this.tnom.getText();
        String cat = this.tcat.getText();
        
        Stock es = new Stock(llocid,prodid);
        
                int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog (null, "¿Estas seguro de eliminar el producto "+cat+": "+nom+"?","Warning",dialogButton);
   
                if(dialogResult == 0){ 
                    producto.delProductoStockLugar(es);
                    this.jTable1.setModel(producto.mostrarProducto());
                    producto.ocultarColumna(7, jTable1);
                    producto.ocultarColumna(8, jTable1);
                    producto.ocultarColumna(9, jTable1);
                    producto.ocultarColumna(10, jTable1);
                    producto.ocultarColumna(11, jTable1);
                    producto.ocultarColumna(12, jTable1);
                    this.jTable2.setModel(producto.mostrarLocalizacion());
                } else {
                    return;
                }
    }//GEN-LAST:event_bteliminarActionPerformed

    private void btbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbuscarActionPerformed
        // TODO add your handling code here:
        String bus = this.tbuscar.getText();        
        
        int op = this.jComboBox5.getSelectedIndex();
        
        
        this.jTable1.setModel(producto.buscar(bus,op));
        producto.ocultarColumna(7, jTable1);
        producto.ocultarColumna(8, jTable1);
        producto.ocultarColumna(9, jTable1);
        producto.ocultarColumna(10, jTable1);
        producto.ocultarColumna(11, jTable1);
        producto.ocultarColumna(12, jTable1);
        this.jTable2.setModel(producto.buscarLoc(bus,op));
    }//GEN-LAST:event_btbuscarActionPerformed

    private void jComboBox5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox5ItemStateChanged
        // TODO add your handling code here:
        this.tbusop.setText((String)this.jComboBox5.getSelectedItem());
    }//GEN-LAST:event_jComboBox5ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.jTable3.setModel(mostrarPersona());
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Conexion conecControl = new Conexion();
        Connection cn = conecControl.conectar();

        String sql = "INSERT INTO tbl_personas (persona_usuario, persona_password) VALUES (?,?)";
       
        PreparedStatement pst1 = null;
       
        
       
        
        ResultSet rs = null;
        
        try {
         
  
//insertar registros a la tbl_producte

            pst1 = cn.prepareStatement(sql);

            pst1.setString(1, this.jTextField1.getText());
            pst1.setString(2, this.jTextField2.getText());
          
            
            pst1.executeUpdate();
            //JOptionPane.showMessageDialog(null, "Producto");
            

            JOptionPane.showMessageDialog(null, "Registro añadido correctamente.");

           this.jTable3.setModel(mostrarPersona()); 
         
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Conexion erronea");
            
        }
    }
    
    
    public void delProductoStockLugar(Stock es){
  
        Conexion conecControl = new Conexion();
        Connection cn = conecControl.conectar();
        
        String sql = "DELETE FROM tbl_estoc WHERE prod_id = ? ";
        String sql2 = "DELETE FROM tbl_producte WHERE prod_id = ?";
        String sql3 = "DELETE FROM tbl_lloc WHERE lloc_id = ?";
        
        PreparedStatement pst = null;
        PreparedStatement pst2 = null;
        PreparedStatement pst3 = null;
         
        try {
            cn.setAutoCommit(false);
            
            pst = cn.prepareStatement(sql);

            pst.setInt(1, es.getProd_id());
            
            pst.executeUpdate();
            
            /*if (n!=0){
            JOptionPane.showMessageDialog(null, "Borrado stock");
            }else{
            JOptionPane.showMessageDialog(null, "NO Borrado stock");
            }*/
           // 
            pst2 = cn.prepareStatement(sql2);
            
            pst2.setInt(1, es.getProd_id());
            
            pst2.executeUpdate();
            
            /*if (m!=0){
            JOptionPane.showMessageDialog(null, "Borrado producto");
            }else{
            JOptionPane.showMessageDialog(null, "NO Borrado producto");
            }*/
            //
            pst3 = cn.prepareStatement(sql3);
            
            pst3.setInt(1, es.getLloc_id());
            
            pst3.executeUpdate();
            
            /*if (o!=0){
            JOptionPane.showMessageDialog(null, "Borrado lloc");
            }else{
            JOptionPane.showMessageDialog(null, "NO Borrado lloc");
            }*/
            
            JOptionPane.showMessageDialog(null, "Se ha eliminado el registro.");
            
            cn.commit();
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Conexion erronea");
            try {
                cn.rollback();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "No se puede deshacer");
            }          
        }
    }
    
    public void modProductoStockLloc(Stock es, Producto p, Lugar l){
        
        Conexion conecControl = new Conexion();
        Connection cn = conecControl.conectar();
        
        String sql = "UPDATE tbl_producte SET prod_nom = ?, prod_serie = ?, categoria_id = ? WHERE prod_id = ?";
        String sql2 = "UPDATE tbl_lloc SET num_bloc = ?, num_passadis = ?, num_lleixa = ? WHERE lloc_id = ?";
        String sql3 = "UPDATE tbl_estoc SET estoc_q_actual = ?, estoc_q_min = ?, estoc_q_max = ? WHERE prod_id =?";
        
        PreparedStatement pst = null;
        PreparedStatement pst2 = null;
        PreparedStatement pst3 = null;
        
        try {
            cn.setAutoCommit(false);
        //    
            pst = cn.prepareStatement(sql);
            
            pst.setString(1, p.getProd_nom());
            pst.setString(2, p.getProd_serie());
            pst.setInt(3, p.getCategoria_id());
            pst.setInt(4, es.getProd_id());
            
            pst.executeUpdate();
            
            /*if (n!=0){
            JOptionPane.showMessageDialog(null, "cambiado producto");
            }else{
            JOptionPane.showMessageDialog(null, "no cmabiado prod");
            }*/
        //    
            pst2 = cn.prepareStatement(sql2);
            
            pst2.setString(1, l.getNum_bloc());
            pst2.setString(2, l.getNum_passadis());
            pst2.setString(3, l.getNum_lleixa());
            pst2.setInt(4, es.getLloc_id());
            
            pst2.executeUpdate();
            
            /*if (m!=0){
            JOptionPane.showMessageDialog(null, "cambiado lugar");
            }else{
            JOptionPane.showMessageDialog(null, "NO cambiado lugar");
            }*/
        //
            pst3 = cn.prepareStatement(sql3);
            
            pst3.setInt(1, es.getEstoc_q_actual());
            pst3.setInt(2, es.getEstoc_q_min());
            pst3.setInt(3, es.getEstoc_q_max());
            pst3.setInt(4, es.getProd_id());
            
            pst3.executeUpdate();
            
            /*if (o!=0){
            JOptionPane.showMessageDialog(null, "cambiado estoc");
            }else{
            JOptionPane.showMessageDialog(null, "no cambiado estoc");
            }*/
        //  
            JOptionPane.showMessageDialog(null, "Se ha modificado el registro.");    
        
            cn.commit();
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Conexion erronea");
            try {
                cn.rollback();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "No se puede deshacer");
            }          
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int fila;
        fila=this.jTable3.getSelectedRow();
        JOptionPane.showMessageDialog(null,fila);
        if(fila==-1){
        JOptionPane.showMessageDialog(null,fila);
        }
        else{
            String nombre=(String)this.jTable3.getValueAt(fila, 0);
            String password=(String)this.jTable3.getValueAt(fila, 1);
            this.jTextField1.setText(nombre);
             this.jTextField2.setText(password);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
         int fila=this.jTable3.getSelectedRow();
        JOptionPane.showMessageDialog(null,fila);
       
            String nombre=(String)this.jTable3.getValueAt(fila, 0);
            String password=(String)this.jTable3.getValueAt(fila, 1);
            this.jTextField1.setText(nombre);
             this.jTextField2.setText(password);
        
    }//GEN-LAST:event_jTable3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vistaProducto frame = new vistaProducto(); 
                frame.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea aerror;
    private javax.swing.JButton btadd_mod;
    private javax.swing.JButton btbuscar;
    private javax.swing.JButton bteliminar;
    private javax.swing.JButton btnuevo;
    private javax.swing.JTextField estocid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField llocid;
    private javax.swing.JPanel pform;
    private javax.swing.JPanel ptabla;
    private javax.swing.JTextField tbloc;
    private javax.swing.JTextField tbuscar;
    private javax.swing.JTextField tbusop;
    private javax.swing.JTextField tcat;
    private javax.swing.JTextField testanteria;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tidcat;
    private javax.swing.JTextField tnom;
    private javax.swing.JTextField tpasadizo;
    private javax.swing.JTextField tserie;
    private javax.swing.JTextField tstockactual;
    private javax.swing.JTextField tstockmax;
    private javax.swing.JTextField tstockmin;
    // End of variables declaration//GEN-END:variables
}
